# Header
menu:
  Sobre: /about
  Dicionário: /2020/12/04/dicionario-seguranca/
  Links: /links
  Tags: /tags
  Github:  
    url: https://github.com/gadotti
    icon: github
  Linkedin:
    url: https://www.linkedin.com/in/eduardogadotti/
    icon: linkedin
  Youtube:
    url: https://www.youtube.com/user/chervesblezz
    icon: youtube
  RSS:
    url: https://eduardogadotti.com/rss2.xml
    icon: rss

# Title on top left of menu. Leave empty to use main blog title
menu_title: 'Home'

# URL of the Home page image
index_cover: /imgs/cover/cover.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments: false

# Google Analytics Tracking ID
google_analytics: G-7TZDPE0QBV

# Addthis ID
addthis:

# set your own favicon
favicon: favicon.ico

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/gadotti
gitlab_url:
linkedin_url: https://www.linkedin.com/in/eduardogadotti/
mailto: gadotti.eduardo@gmail.com