logo_title: Eduardo Gadotti

style: black

favicon: /favicon.ico

menu:
  Sobre: /about
  LinkedIn: https://www.linkedin.com/in/eduardogadotti
  Youtube: https://www.youtube.com/user/chervesblezz
  Github: https://github.com/gadotti

valine:
  enable: false
  appId:
  appKey:

highlight:
  enable: false